# Lang
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_NUMERIC=nl_NL.UTF-8
export LC_TIME=nl_NL.UTF-8
export LC_MONETARY=nl_NL.UTF-8
export LC_PAPER=nl_NL.UTF-8
export LC_ADDRESS=nl_NL.UTF-8
export LC_MEASUREMENT=nl_NL.UTF-8
export LC_TELEPHONE=nl_NL.UTF-8
