# Lang
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_NUMERIC=en_NL.UTF-8
export LC_TIME=en_NL.UTF-8
export LC_MONETARY=en_NL.UTF-8
export LC_PAPER=en_NL.UTF-8
export LC_ADDRESS=en_NL.UTF-8
export LC_MEASUREMENT=en_NL.UTF-8
export LC_TELEPHONE=en_NL.UTF-8
