PATH=$PATH:\
./vendor/bin:\
./node_modules/.bin:\
$HOME/.yarn/bin:\
$HOME/bin:\
$HOME/.local/bin:\
/usr/local/opt/coreutils/libexec/gnubin/:\
/usr/local/sbin:\
/usr/local/bin:\
/usr/bin:\
/bin:\
/usr/sbin/:\
/sbin:\
$GEM_HOME/bin:\
$HOME/.composer/vendor/bin:\
$GOPATH/bin:\
$GOROOT/bin:\
$HOME/Library/Python/3.7/bin:\
$HOME/.rvm/bin
